CXX = clang++
CXXFLAGS = -std=c++20 -O3 \
		   -MMD -MP \
		   -I./include \
		   -I./include/GLEW \
		   -I./include/glm \
		   -I./include/SDL2 -I./include/SDL2/SDL2 \
		   -I./include/SDL2_mixer \
		   -I./include/SDL2_ttf \
		   -I./include/stb \
		   -g \
		   -fdiagnostics-color=always \
		   -Wextra \
		   -Wall \
		   -Wuninitialized \
		   -Winit-self \
		   -Wfloat-equal \
		   -Wundef \
		   -Wpointer-arith \
		   -Wcast-align \
		   -Wstrict-overflow=5 \
		   -Wwrite-strings \
		   -Wcast-qual \
		   -Wswitch-default \
		   -Wconversion \
		   -Wunreachable-code

LDFLAGS = -L./lib/GLEW \
		  -L./lib/SDL2 \
		  -L./lib/SDL2_mixer \
		  -L./lib/SDL2_ttf \
		  -L./build \
		  -lGL -lGLEW -lSDL2 -lSDL2_mixer -lSDL2_ttf -lscarablib

# Dirs
BUILD_DIR = build
TESTOBJS_DIR = $(BUILD_DIR)/testobjs

# Files
SRC_FILES = $(wildcard test/*.cpp)
TESTOBJS = $(patsubst test/%.cpp, $(TESTOBJS_DIR)/%.o, $(SRC_FILES))
TEST_FILE = test/main.cpp

TARGET = scarablib

all: dev

dev: $(TESTOBJS)
	$(CXX) $(CXXFLAGS) $^ -o $(BUILD_DIR)/$(TARGET) $(LDFLAGS)

$(TESTOBJS_DIR)/%.o: test/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -rf $(BUILD_DIR)/$(TARGET) $(TESTOBJS_DIR)

.PHONY: all clean dev
